###########################################################################
# Dockerfile - Fluentd configuration
###########################################################################


FROM fluent/fluentd:v1.16-1

# File Author / Maintainer
LABEL org.medium.image.authors="tauseef"
COPY /maven/fluentd.conf /fluentd/etc/